default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: monchifc
  password: <%= ENV['MONCHIFC_DATABASE_PASSWORD'] %>
  timeout: 5000
  

development:
  <<: *default
  database: monchifc_development

test:
  <<: *default
  database: monchifc_test

production:
  <<: *default
  database: monchifc_production
  username: monchifc
  password: <%= ENV['MONCHIFC_DATABASE_PASSWORD'] %>
